language: groovy

jdk:
- oraclejdk7

script:
- ./grailsw refresh-dependencies
- ./grailsw -Dgrails.env=travis_ci test-app -coverage -xml

deploy:

  provider: heroku
  api_key: "88302bfb-c539-4b2d-a34a-f72e25bbe43d"
  app: ivvq-split
    secure:

